[build]
  command = "npm run netlify-build"
  publish = "out"

# Build environment variables
[build.environment]
  NETLIFY_USE_YARN = "false"
  NODE_VERSION = "20.11.1"
  NEXT_TELEMETRY_DISABLED = "1"

# Force trailing slashes
[[plugins]]
  package = "netlify-plugin-checklinks"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Cache-Control = "public, max-age=0, must-revalidate" 