[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# These redirects are not needed with the Next.js plugin and can cause issues
# [[redirects]]
#  from = "/*"
#  to = "/index.html"
#  status = 200 